# --- Fuentes ---
font_family      JetBrainsMono NFM
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

# --- Apariencia ---
# Elige la transparencia que más te guste (0.85 es un buen punto medio)
background_opacity 0.97

# Margen para que el texto no esté pegado a los bordes
window_padding_width 10

# --- Comportamiento ---
# Esto ayuda a que Starship y otros temas funcionen mejor
shell_integration enabled

# El cursor (puntero) como una barrita nítida
cursor_shape beam

map ctrl+v paste_from_clipboard


# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
